### ISSUE TITLE
Update payload power supply section in the design document 

### ISSUE THREAD

**Issue by FSXAC** [Capstone-Skynet/Capstone-Skynet.github.io#71]
Update and consolidate the "power supply" section in the design document (3_1_7_computing_power.tex) and also update the diagram used (Power_Diagram.png).

**Comment by peterdeutsch** [comment]
@ardell96 @wzfftxwd Do either of you have the bandwidth to take this on? I might have some time tomorrow morning, but I'm not the expert on this section.
