### ISSUE TITLE
Footnotes and citations are ambiguous

### ISSUE THREAD

**Issue by FSXAC** [Capstone-Skynet/Capstone-Skynet.github.io#80]
Current LaTeX style does not differentiate the style between \footnote and \cite. Need to update this so that readers know which one is which

**Comment by peterdeutsch** [comment]
This is a perennial annoyance with my tex templates. I don't think it's worth re-jigging the document to fix it, whether something is a footnote or citation should be obvious to the reader by the footnote's presence (or lack thereof).

**Comment by peterdeutsch** [comment]
Closing as won't fix
